# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\gui\\../assets/lock.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lockImage = QtWidgets.QLabel(self.centralwidget)
        self.lockImage.setText("")
        self.lockImage.setObjectName("lockImage")
        self.verticalLayout.addWidget(self.lockImage)
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.encryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.encryptButton.setObjectName("encryptButton")
        self.verticalLayout.addWidget(self.encryptButton)
        self.decryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.decryptButton.setObjectName("decryptButton")
        self.verticalLayout.addWidget(self.decryptButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "file Guard"))
        self.passwordInput.setPlaceholderText(_translate("MainWindow", "Password"))
        self.encryptButton.setText(_translate("MainWindow", "Encrypt"))
        self.decryptButton.setText(_translate("MainWindow", "Decrypt"))
